import {getUser,login,signup,logout,handleAuthCallback,getSettings,requestPasswordRecovery,updateUser,acceptInvite,onAuthChange} from './vendor/identity.mjs';
import {ShootoutScene} from './football-scene.mjs';
import {SniperScene} from './sniper-scene.mjs';
import {TurkeyFightScene} from './turkey-scene.mjs';
import {PENALTY_MOVES,TURKEY_MOVES,SNIPER_SPOTS} from './game-engine.mjs';
import {footballRoundLabel} from './game-rules.mjs';
import {poolStore} from './question-pools.mjs';
import {readQuestionDocument} from './document-reader.mjs';
import {cleanQuestion,validateQuestion,parseQuestionText,parseCsv,parsePoolJson} from './question-import.mjs';

const root=document.getElementById('classroom-root'), nav=document.getElementById('app-nav');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=v=>String(v).split('-').map(w=>w[0]?.toUpperCase()+w.slice(1)).join(' ');
const gameName=g=>({penalty:'Football',turkey:'Turkey Fight',sniper:'Sniper'}[g]);
let session=null, dashboard=null, activeTab='matches', scene=null, routeId=0, polling=null, currentMatch=null, draft=null, authMode='login', installPrompt=null;
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const params=new URLSearchParams(location.search);
if(params.get('join'))sessionStorage.setItem('mailgames.join',params.get('join'));
const notice=(message,error=false)=>{const n=document.getElementById('app-notice');n.textContent=message;n.classList.toggle('error',error);n.hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>n.hidden=true,error?12000:6500);};
async function api(action='dashboard',data={}) {
  const response=await fetch('/api/classroom',action==='dashboard'?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});
  let result;try{result=await response.json();}catch{throw new Error('The classroom service is unavailable. Please retry.');}
  if(!response.ok)throw Object.assign(new Error(result.error||'Could not complete this request.'),{status:response.status});
  return result;
}
function cleanView(){routeId++;clearInterval(polling);polling=null;scene?.destroy?.();scene=null;currentMatch=null;}
function setView(html){cleanView();root.innerHTML=html;}
function busyForm(id,action){const form=document.getElementById(id);form?.addEventListener('submit',async event=>{event.preventDefault();const submit=form.querySelector('[type=submit]');if(submit?.disabled)return;if(submit)submit.disabled=true;try{await action(new FormData(form),form);}catch(e){notice(e.message,true);}finally{if(submit?.isConnected)submit.disabled=false;}});}
function click(selector,fn){document.querySelectorAll(selector).forEach(el=>el.addEventListener('click',async e=>{e.preventDefault();if(el.disabled)return;el.disabled=true;try{await fn(el,e);}catch(error){notice(error.message,true);}finally{if(el.isConnected)el.disabled=false;}}));}
function updateNav(){nav.innerHTML=session?`<span>${esc(dashboard?.user?.name||session.name||session.email)}</span><button class="quiet" id="home-app">My classroom</button><button class="quiet" id="sign-out">Sign out</button>`:'<a href="index.html">Email & classroom demos ↗</a>';click('#sign-out',async()=>{if('serviceWorker' in navigator){const r=await navigator.serviceWorker.getRegistration();const sub=await r?.pushManager?.getSubscription();if(sub){try{await api('unsubscribe',{subscription:{endpoint:sub.endpoint}});}catch{}await sub.unsubscribe();}}await logout();session=null;dashboard=null;location.replace('classroom.html');});click('#home-app',()=>home());}
function preview(){const canvas=document.getElementById('welcome-pitch');if(canvas){scene=new ShootoutScene(canvas,null,{reducedMotion:true});scene.setIdle({caption:''});}}
const welcome=()=>`<div class="hero"><div><span class="eyebrow">A question. A move. Your turn.</span><h1>A little rivalry.<br>A lot of learning.</h1><p>Three games. Your teacher’s questions. One more reason to practise English.</p><span class="pill">Football</span> <span class="pill">Turkey Fight</span> <span class="pill">Sniper</span></div><div class="hero-art"><canvas id="welcome-pitch" aria-label="The football stadium"></canvas><div class="label">THE PENALTY CLUB · READY WHEN YOU ARE</div></div></div>`;
async function showAuth(message='') {
  updateNav();setView(`${welcome()}<div class="two-col"><section class="card auth-card"><span class="eyebrow">Your classroom, anywhere</span><h2>${authMode==='signup'?'Create your account':'Welcome back'}</h2><p>${authMode==='signup'?'Use your own email. Your teacher’s joining code connects you to the class.':'Sign in to see your assignments and pick up your next turn.'}</p><form id="auth-form">${authMode==='signup'?'<label>Your name<input name="name" autocomplete="name" maxlength="80" required></label>':''}<label>Email<input name="email" type="email" autocomplete="email" required></label><label>Password<input name="password" type="password" autocomplete="${authMode==='signup'?'new-password':'current-password'}" minlength="10" required></label><button class="primary" type="submit">${authMode==='signup'?'Create account':'Sign in'}</button></form><div class="toolbar"><button class="quiet" id="switch-auth">${authMode==='signup'?'Already have an account? Sign in':'New here? Create an account'}</button><button class="quiet" id="forgot-password">Forgot password?</button></div><p id="auth-status" class="form-error" role="status">${esc(message)}</p></section><section class="card tint"><span class="eyebrow">How it works</span><h2>Your next turn is waiting.</h2><div class="row"><strong>01</strong><div>Join your class<small><br>Use the personal code your teacher gives you.</small></div></div><div class="row"><strong>02</strong><div>Answer & choose a move<small><br>A correct answer activates your move. Your choice stays secret.</small></div></div><div class="row"><strong>03</strong><div>Watch the replay<small><br>Take turns until the match ends. Your teacher sees the results.</small></div></div><p class="account-note">Teachers: create an account, then activate your teacher workspace with your private teacher code.</p></section></div>`);preview();
  click('#switch-auth',()=>{authMode=authMode==='signup'?'login':'signup';showAuth();});
  busyForm('auth-form',async data=>{
    if(authMode==='signup'){
      await signup(String(data.get('email')),String(data.get('password')),{full_name:String(data.get('name'))});session=await getUser();
      if(!session){authMode='login';await showAuth('Check your email and confirm your account, then sign in.');return;}
    }else session=await login(String(data.get('email')),String(data.get('password')));
    await home();
  });
  click('#forgot-password',async()=>{const email=document.querySelector('[name=email]').value;if(!email)throw new Error('Enter your email first.');await requestPasswordRecovery(email);notice('If an account exists, a password reset email is on its way.');});
  try{await getSettings();}catch{const status=document.getElementById('auth-status');if(status)status.textContent='Accounts need to be enabled in Netlify Identity before sign-in can work. You can still use the email and classroom demos.';}
}
async function passwordScreen(callback){setView(`<section class="card auth-card"><h1>Set your password</h1><form id="password-form"><label>New password<input name="password" type="password" minlength="10" autocomplete="new-password" required></label><button class="primary" type="submit">Save password</button></form></section>`);busyForm('password-form',async data=>{if(callback.type==='invite')await acceptInvite(callback.token,String(data.get('password')));else await updateUser({password:String(data.get('password'))});session=await getUser();await home();});}
async function home(){
  const url=new URL(location);url.searchParams.delete('match');url.searchParams.delete('teacher');history.replaceState(null,'',url);currentMatch=null;
  if(!session){await showAuth();return;}
  try{dashboard=await api();}catch(e){updateNav();setView(`<section class="card"><h2>We couldn’t open your classroom yet.</h2><p>${esc(e.message)}</p><button class="primary" id="retry-home">Try again</button> <a href="index.html">Open classroom demos</a></section>`);click('#retry-home',home);return;}
  updateNav();renderHome();
}
function renderHome(){
  const isTeacher=dashboard.user.role==='teacher', w=dashboard.workspace;
  const matches=isTeacher?w.matches:dashboard.matches;
  setView(`<div class="toolbar"><span class="pill">${isTeacher?'Teacher workspace':'Student clubhouse'}</span><span class="muted">${isTeacher?`${w.classes.length} classes · ${w.pools.length} cloud pools`:`${dashboard.memberships.length} classes joined`}</span></div><div class="row" style="border:0;align-items:end"><div><h1>${isTeacher?'Make learning a team sport.':'Your next move.'}</h1><p class="muted">${isTeacher?'Choose the questions. Pair your players. Follow their progress.':'Answer well. Play smart. Come back when it’s your turn.'}</p></div><button class="secondary" id="account-settings">Notifications</button></div>${isTeacher?`<div class="tabs" role="tablist" aria-label="Teacher workspace">${['matches','classes','pools','results'].map(t=>`<button role="tab" aria-selected="${activeTab===t}" data-tab="${t}">${title(t)}</button>`).join('')}</div>`:''}<section id="workspace-content"></section>${!isTeacher?'<section class="two-col" style="margin-top:28px"><div class="card" id="join-card"></div><div class="card tint"><h2>Playing on a phone?</h2><p>Add Mail Games to your home screen. Enable notifications on this device to hear when your next turn is ready.</p><p class="muted">Your match also stays in this inbox, so you can play even with notifications switched off.</p><details><summary>I’m a teacher</summary><form id="teacher-activate"><label>Private teacher code<input name="code" type="password" autocomplete="off" required></label><button class="primary" type="submit">Activate teacher workspace</button></form></details></div></section>':''}`);
  click('[data-tab]',el=>{activeTab=el.dataset.tab;renderHome();});click('#account-settings',notificationDialog);
  if(!isTeacher){renderMatches(matches,false);renderJoin();busyForm('teacher-activate',async data=>{await api('activate-teacher',{code:data.get('code')});await home();});}
  else if(activeTab==='classes')renderClasses();else if(activeTab==='pools')renderPools();else if(activeTab==='results')renderResults();else renderMatches(matches,true);
  const view=routeId;polling=setInterval(async()=>{if(document.hidden || routeId!==view)return;try{const next=await api();const oldStamp=JSON.stringify((isTeacher?dashboard.workspace.matches:dashboard.matches).map(m=>[m.id,m.version,m.cancelled]));const newStamp=JSON.stringify((isTeacher?next.workspace.matches:next.matches).map(m=>[m.id,m.version,m.cancelled]));dashboard=next;if(oldStamp!==newStamp && (!isTeacher || activeTab==='matches'))renderHome();}catch{}},20000);
}
function renderJoin(){const el=document.getElementById('join-card');el.innerHTML=`<span class="eyebrow">Join the team</span><h2>Have a class code?</h2><form id="join-form"><label>Your personal joining code<input name="code" autocomplete="off" maxlength="40" value="${esc(sessionStorage.getItem('mailgames.join')||'')}" placeholder="Given to you by your teacher" required></label><button type="submit" class="primary">Join class</button></form>${dashboard.memberships.map(m=>`<p class="pill">${esc(m.name)}</p>`).join('')}`;busyForm('join-form',async data=>{await api('join',{code:data.get('code')});sessionStorage.removeItem('mailgames.join');notice('You’ve joined your class.');await home();});}
function renderMatches(matches,isTeacher){
  const el=document.getElementById('workspace-content');const ordered=[...matches].sort((a,b)=>Number(b.myTurn)-Number(a.myTurn)||Number(a.finished||a.cancelled)-Number(b.finished||b.cancelled)||b.createdAt-a.createdAt);
  el.innerHTML=`${isTeacher?'<div class="toolbar"><button class="primary" id="new-assignment">＋ Assign a match</button><span class="muted">Students use their own devices. No turn emails required.</span></div>':''}<div class="grid">${ordered.map(m=>{const own=m.actor;return `<article class="card"><div class="toolbar" style="margin-top:0"><span class="eyebrow" style="margin:0">${gameName(m.gameType)}</span><span class="pill ${m.myTurn?'turn':''}">${m.myTurn?'Your turn':m.finished||m.cancelled?esc(m.outcome):'In progress'}</span></div><h2>${esc(m.title)}</h2><p>${esc(m.players.A.name)} <span class="muted">vs</span> ${esc(m.players.B.name)}</p><div class="scorebar"><strong>${m.gameType==='penalty'?`${m.scoreA} – ${m.scoreB}`:`${m.healthA} : ${m.healthB}`}</strong><small>${m.gameType==='penalty'?footballRoundLabel({...m,...m.settings}):`Round ${Math.min(m.round,m.settings.maxRounds)} of ${m.settings.maxRounds}`}</small></div><p class="muted">${m.finished||m.cancelled?'Match ended. Results are saved.':`${esc(m.players[m.currentActor].name)} plays next${m.gameType==='penalty'?` as ${m.role==='striker'?'shooter':'goalkeeper'}`:''}.`}</p><button class="${m.myTurn?'primary':'secondary'}" data-open-match="${m.id}" data-teacher="${m.teacherId}">${isTeacher?'View progress':m.myTurn?'Play your turn →':m.finished?'See results':'Open match'}</button>${own?`<small style="display:block;margin-top:16px">Your English: ${m.accuracy[own].correct} / ${m.accuracy[own].total} correct</small>`:''}</article>`;}).join('')||`<div class="card empty"><h2>${isTeacher?'Your first match starts here.':'No matches just yet.'}</h2><p>${isTeacher?'Add a class and students, save a question pool, then assign a match.':'Join your class below. Your teacher’s assignments will appear here.'}</p></div>`}</div>`;
  click('[data-open-match]',el=>openMatch(el.dataset.teacher,el.dataset.openMatch));click('#new-assignment',renderAssignment);
}
function renderClasses(){
  const classes=dashboard.workspace.classes;
  document.getElementById('workspace-content').innerHTML=`<div class="two-col"><section class="card"><h2>Your classes</h2><form id="new-class"><label>Class name<input name="name" placeholder="Year 8 · Tuesday English" maxlength="100" required></label><button class="primary" type="submit">Create class</button></form>${classes.map(c=>`<div class="row"><div><strong>${esc(c.name)}</strong><small><br>${c.students.filter(s=>!s.archived).length} students</small></div><button class="secondary" data-class="${c.id}">Manage roster</button></div>`).join('')}</section><section class="card tint"><span class="eyebrow">Teacher-led enrolment</span><h2>A personal code for every student.</h2><p>Add names to your class. Give each student their own joining code. They create an account and enter the code once.</p><p>Students who haven’t joined yet cannot be assigned a match. Joining codes expire after seven days; you can issue a fresh one.</p></section></div>`;
  busyForm('new-class',async data=>{await api('class-create',{name:data.get('name')});await home();});click('[data-class]',el=>renderRoster(el.dataset.class));
}
function renderRoster(id){const c=dashboard.workspace.classes.find(c=>c.id===id);document.getElementById('workspace-content').innerHTML=`<div class="toolbar"><button class="quiet" id="back-classes">← Classes</button><h2 style="margin:0">${esc(c.name)}</h2></div><div class="two-col"><section class="card"><h3>Add students</h3><form id="roster-add"><label>Names — one per line<textarea name="names" rows="5" placeholder="Ada\nMert\nSam" required></textarea></label><button class="primary" type="submit">Create joining codes</button></form><div id="new-codes" role="status"></div></section><section class="card"><h3>Class roster</h3>${c.students.filter(s=>!s.archived).map(s=>`<div class="row"><div><strong>${esc(s.name)}</strong><small><br>${s.userId?'Joined ✓':'Waiting to join'}</small></div><div class="row-actions">${!s.userId?`<button class="quiet" data-code="${s.id}">New code</button>`:''}<button class="quiet" data-remove="${s.id}">Remove</button></div></div>`).join('')||'<p class="muted">Add your first students on the left.</p>'}</section></div>`;
  click('#back-classes',renderClasses);
  const showCodes=async result=>{dashboard=await api();renderRoster(id);document.getElementById('new-codes').innerHTML=`<h3 style="margin-top:24px">Give each student only their own code</h3><p class="muted">Save these now. For security, existing codes are not shown again.</p>${result.invites.map(s=>`<div class="row"><strong>${esc(s.name)}</strong><code class="code">${s.code.match(/.{1,6}/g).join('-')}</code></div>`).join('')}<button class="secondary" id="download-codes">Download joining codes</button>`;click('#download-codes',()=>downloadCsv('class-joining-codes.csv',[['Student','Joining code','Join at'],...result.invites.map(s=>[s.name,s.code,new URL(`classroom.html?join=${s.code}`,location.href).href])]));};
  busyForm('roster-add',async data=>showCodes(await api('roster-add',{classId:id,names:data.get('names')})));
  click('[data-code]',async el=>showCodes(await api('roster-code',{classId:id,studentId:el.dataset.code})));
  click('[data-remove]',async el=>{if(!confirm('Remove this student and end their active matches in this class?'))return;await api('roster-remove',{classId:id,studentId:el.dataset.remove});dashboard=await api();renderRoster(id);});
}
function renderPools(){const pools=dashboard.workspace.pools;let local=[];try{local=poolStore.list().pools.filter(p=>p.questions.length);}catch{}
  document.getElementById('workspace-content').innerHTML=`<div class="toolbar"><button class="primary" id="new-pool">＋ New question pool</button><label style="margin:0" class="secondary">Import PDF / Word / pool<input id="cloud-import" type="file" accept=".pdf,.docx,.json,.csv,.txt" hidden></label><span id="cloud-import-status" role="status"></span></div><div class="grid">${pools.map(p=>`<article class="card"><span class="eyebrow">Saved to your teacher account</span><h2>${esc(p.name)}</h2><p>${p.questions.length} questions · ${[...new Set(p.questions.map(q=>q.level))].join(', ')}</p><button class="secondary" data-edit-pool="${p.id}">Edit questions</button> <button class="quiet" data-delete-pool="${p.id}">Delete</button></article>`).join('')||'<article class="card empty"><h2>Bring your questions.</h2><p>Create your own, upload a document, or copy a pool from this browser.</p></article>'}</div><details><summary>Copy an existing pool from this browser (${local.length})</summary><p>Copying saves it to your teacher account for use on other devices.</p>${local.map((p,i)=>`<button class="secondary" data-copy-pool="${i}">${esc(p.name)} · ${p.questions.length} questions</button>`).join(' ')}</details><p class="muted">Import text-based PDFs, Word .docx, CSV, JSON or TXT. Review the answer key before saving. Scanned pages need OCR first; save older .doc files as .docx.</p>`;
  click('#new-pool',()=>poolEditor({name:'',questions:[cleanQuestion()]}));click('[data-edit-pool]',el=>poolEditor(structuredClone(pools.find(p=>p.id===el.dataset.editPool))));click('[data-copy-pool]',el=>{const p=local[Number(el.dataset.copyPool)];poolEditor({name:p.name,questions:structuredClone(p.questions)});});click('[data-delete-pool]',async el=>{if(!confirm('Delete this pool? Assigned matches keep their question copies.'))return;await api('pool-delete',{id:el.dataset.deletePool});await home();});
  document.getElementById('cloud-import').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;const status=document.getElementById('cloud-import-status');event.target.disabled=true;try{const {text,ext}=await readQuestionDocument(file,message=>status.textContent=message);const qs=ext==='json'?parsePoolJson(text):ext==='csv'?parseCsv(text):parseQuestionText(text);if(!qs.length)throw new Error('No questions found. Try a numbered question list with its answer key.');if(qs.length>200)throw new Error('Import up to 200 questions per cloud pool.');poolEditor({name:file.name.replace(/\.[^.]+$/,''),questions:qs});}catch(e){notice(e.message,true);event.target.disabled=false;}};
}
function poolEditor(pool){draft=pool;const el=document.getElementById('workspace-content');
  el.innerHTML=`<div class="toolbar"><button class="quiet" id="cancel-pool">← Question pools</button><span class="pill">${pool.id?'Edit pool':'Review before saving'}</span></div><section class="card"><form id="pool-editor"><label>Pool name<input name="name" value="${esc(pool.name)}" required maxlength="100"></label><p class="muted">Check the full question, options and correct answer. Assigned matches keep their original copies when you edit a pool.</p><div id="question-editors"></div><div class="toolbar"><button type="button" class="secondary" id="add-cloud-question">＋ Add question</button><button class="primary" type="submit">Save to my teacher account</button></div><p id="pool-errors" class="form-error" role="status"></p></form></section>`;
  function sync(){pool.name=document.querySelector('#pool-editor [name=name]').value;document.querySelectorAll('[data-question-index]').forEach(box=>{const q=pool.questions[Number(box.dataset.questionIndex)];box.querySelectorAll('[data-field]').forEach(input=>q[input.dataset.field]=input.dataset.field==='options'?input.value.split('\n').map(x=>x.trim()).filter(Boolean):input.value);});}
  function fields(){document.getElementById('question-editors').innerHTML=pool.questions.map((q,i)=>`<div class="question-editor" data-question-index="${i}"><div class="row"><h3>Question ${i+1}</h3><button class="quiet" type="button" data-remove-question="${i}">Remove</button></div><label>Question<textarea data-field="prompt" maxlength="1000" required>${esc(q.prompt)}</textarea></label><div class="field-pair"><label>Type<select data-field="type">${['multiple-choice','true-false','gap-fill'].map(t=>`<option ${t===q.type?'selected':''}>${t}</option>`).join('')}</select></label><label>Level<select data-field="level">${['A1','A2','B1','B2','C1','C2'].map(t=>`<option ${t===q.level?'selected':''}>${t}</option>`).join('')}</select></label></div><label>Options — one per line (leave empty for gap-fill)<textarea data-field="options">${esc((q.options||[]).join('\n'))}</textarea></label><label>Correct answer — exact option text<input data-field="answer" value="${esc(q.answer)}" maxlength="500" required></label><div class="field-pair"><label>Explanation<input data-field="explanation" value="${esc(q.explanation)}" maxlength="1000"></label><label>Topic<input data-field="tag" value="${esc(q.tag)}" maxlength="80"></label></div></div>`).join('');click('[data-remove-question]',el=>{sync();pool.questions.splice(Number(el.dataset.removeQuestion),1);fields();});}
  fields();click('#cancel-pool',renderPools);click('#add-cloud-question',()=>{sync();pool.questions.push(cleanQuestion());fields();document.querySelector('.question-editor:last-child')?.scrollIntoView({block:'start',behavior:'smooth'});});
  busyForm('pool-editor',async()=>{sync();const errors=pool.questions.flatMap((q,i)=>validateQuestion(q).map(e=>`Question ${i+1}: ${e}`));if(!pool.questions.length)errors.push('Add at least one question.');document.getElementById('pool-errors').textContent=errors.join(' ');if(errors.length)return;await api('pool-save',{id:pool.id,version:pool.version,name:pool.name,questions:pool.questions});notice('Question pool saved to your account.');await home();});
}
function renderAssignment(){const w=dashboard.workspace;
  document.getElementById('workspace-content').innerHTML=`<section class="card"><div class="toolbar"><button class="quiet" id="back-matches">← Matches</button><span class="eyebrow" style="margin:0">Teacher match builder</span></div><h2>Two players. One friendly rivalry.</h2><form id="assignment-form"><div class="field-pair"><label>Match title<input name="title" maxlength="100" placeholder="Friday vocabulary challenge"></label><label>Game<select name="gameType"><option value="penalty">Football</option><option value="turkey">Turkey Fight</option><option value="sniper">Sniper</option></select></label></div><div class="field-pair"><label>Class<select name="classId" required><option value="">Choose a class</option>${w.classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Question pool<select name="poolId" required><option value="">Choose a pool</option>${w.pools.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label></div><div class="field-pair"><label><span id="player-a-label">Starting shooter (Player A)</span><select name="playerA" required></select></label><label><span id="player-b-label">Starting goalkeeper (Player B)</span><select name="playerB" required></select></label></div><p class="muted">Only students who have joined appear here. Football roles alternate after every kick.</p><div id="football-settings" class="field-pair"><label>If scores are tied after 5 kicks each<select name="tieMode"><option value="draw">Finish as a draw</option><option value="sudden-death">Continue into sudden death</option></select></label><label>Maximum extra pairs of kicks<input name="extraPairs" type="number" min="1" max="20" value="5"></label></div><label id="round-settings" hidden>Round limit<input name="maxRounds" type="number" min="1" max="20" value="8"></label><p id="rule-summary" class="muted">Both players get equal kicks. If still tied at the extra-pair limit, the match is a draw.</p><details open><summary>Choose questions for this match (up to 100)</summary><div class="toolbar"><button class="quiet" type="button" id="select-questions">Select all</button><button class="quiet" type="button" id="clear-questions">Clear selection</button></div><div id="assignment-questions" class="question-list"></div></details><p class="muted">Questions are shuffled once and repeat only after the selected set has been used. Each student answers on their own turn.</p><button type="submit" class="primary">Assign match to both students →</button></form></section>`;
  click('#back-matches',()=>renderMatches(w.matches,true));const f=document.getElementById('assignment-form');
  f.elements.classId.onchange=()=>{const c=w.classes.find(c=>c.id===f.elements.classId.value);for(const key of ['playerA','playerB'])f.elements[key].innerHTML='<option value="">Choose a student</option>'+(c?.students||[]).filter(s=>s.userId&&!s.archived).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');};
  f.elements.gameType.onchange=()=>{const g=f.elements.gameType.value;document.getElementById('football-settings').hidden=g!=='penalty';document.getElementById('round-settings').hidden=g==='penalty';document.getElementById('player-a-label').textContent=g==='penalty'?'Starting shooter (Player A)':'Player A · first to choose';document.getElementById('player-b-label').textContent=g==='penalty'?'Starting goalkeeper (Player B)':'Player B · second to choose';f.elements.maxRounds.value=g==='turkey'?8:5;document.getElementById('rule-summary').textContent=g==='turkey'?'Most health at the limit wins. Counter stops Peck and Charge and returns 8 damage. Equal health means a draw.':g==='sniper'?'Three health each. Both choices resolve together. Most health at the limit wins.':'Both players get equal kicks. If still tied at the extra-pair limit, the match is a draw.';};
  f.elements.poolId.onchange=()=>{const p=w.pools.find(p=>p.id===f.elements.poolId.value);document.getElementById('assignment-questions').innerHTML=(p?.questions||[]).map((q,i)=>`<label class="check"><input type="checkbox" name="question" value="${q.id}" ${i<100?'checked':''}>${esc(q.prompt)}</label>`).join('');};
  click('#select-questions',()=>f.querySelectorAll('[name=question]').forEach((cb,i)=>cb.checked=i<100));click('#clear-questions',()=>f.querySelectorAll('[name=question]').forEach(cb=>cb.checked=false));
  busyForm('assignment-form',async data=>{const questionIds=data.getAll('question');if(!questionIds.length)throw new Error('Select at least one question.');const body=Object.fromEntries(['title','gameType','classId','poolId','playerA','playerB'].map(k=>[k,data.get(k)]));const result=await api('assign',{...body,questionIds,settings:{tieMode:data.get('tieMode'),extraPairs:Number(data.get('extraPairs')),maxRounds:Number(data.get('maxRounds'))}});notice('Assigned. Both students can see the match in their inbox.');await home();await openMatch(session.id,result.matchId);});
}
function renderResults(){const matches=dashboard.workspace.matches;document.getElementById('workspace-content').innerHTML=`<section class="card"><div class="toolbar"><h2 style="margin:0">Learning & match results</h2><button class="secondary" id="export-results">Download CSV</button></div><div class="table-wrap"><table><thead><tr><th>Match</th><th>Player</th><th>English accuracy</th><th>Result</th><th></th></tr></thead><tbody>${matches.flatMap(m=>['A','B'].map(a=>`<tr><td>${esc(m.title)}<small><br>${gameName(m.gameType)}</small></td><td>${esc(m.players[a].name)}</td><td>${m.accuracy[a].correct} / ${m.accuracy[a].total}${m.accuracy[a].total?` · ${Math.round(100*m.accuracy[a].correct/m.accuracy[a].total)}%`:''}</td><td>${esc(m.outcome)}</td><td><button class="quiet" data-result="${m.id}">Review</button></td></tr>`)).join('')||'<tr><td colspan="5">Results appear as students play.</td></tr>'}</tbody></table></div></section>`;click('[data-result]',el=>openMatch(session.id,el.dataset.result));click('#export-results',()=>downloadCsv('classroom-results.csv',[['Match','Game','Player','Correct','Answered','Outcome'],...matches.flatMap(m=>['A','B'].map(a=>[m.title,gameName(m.gameType),m.players[a].name,m.accuracy[a].correct,m.accuracy[a].total,m.outcome]))]));}
function downloadCsv(name,rows){const csv=rows.map(row=>row.map(v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function openMatch(teacherId,matchId){const result=await api('match',{teacherId,matchId});const url=new URL(location);url.searchParams.set('match',matchId);url.searchParams.set('teacher',teacherId);history.replaceState(null,'',url);renderMatch(result.match);}
function renderMatch(m,afterSubmit=false){
  setView(`<div class="toolbar"><button class="quiet" id="back-home">← My classroom</button><span class="pill">${gameName(m.gameType)}</span><span class="muted">${m.gameType==='penalty'?footballRoundLabel({...m,...m.settings}):`Round ${Math.min(m.round,m.settings.maxRounds)} of ${m.settings.maxRounds}`}</span></div><h1>${esc(m.title)}</h1><div class="match-layout"><section class="card"><div class="scorebar"><div>${esc(m.players.A.name)}<br><strong>${m.gameType==='penalty'?m.scoreA:m.healthA}</strong></div><span class="pill">${m.finished||m.cancelled?esc(m.outcome):'MATCH IN PLAY'}</span><div style="text-align:right">${esc(m.players.B.name)}<br><strong>${m.gameType==='penalty'?m.scoreB:m.healthB}</strong></div></div><canvas class="match-canvas" id="match-canvas" aria-label="Match replay"></canvas><div id="match-caption" class="scene-caption" aria-live="polite"></div><div class="toolbar"><button class="secondary" id="play-last-replay" ${!m.history.length?'disabled':''}>Watch last replay</button><button class="quiet" id="skip-replay" hidden>Skip replay</button></div><small>Your choices stay hidden until both players have committed.</small></section><section class="card" id="match-turn"></section></div><section id="match-review" style="margin-top:24px"></section>`);
  currentMatch=m;const view=routeId;const Scene=m.gameType==='penalty'?ShootoutScene:m.gameType==='sniper'?SniperScene:TurkeyFightScene;
  scene=new Scene(document.getElementById('match-canvas'),document.getElementById('match-caption'),{reducedMotion:reduced()});scene.setIdle({role:m.role,actor:m.actor||'A',caption:'Ready for the next move.'});
  click('#back-home',home);click('#play-last-replay',async()=>playReplay(m.history.at(-1)));click('#skip-replay',()=>{if(scene.skipReplay)scene.skipReplay();else{scene.cancelReplay();scene.progress=1;scene.emitReplayEvents(1);scene.drawSafely(performance.now());}});
  const panel=document.getElementById('match-turn');const latest=m.feedback.at(-1);
  const feedback=latest?`<div class="feedback ${latest.correct?'':'incorrect'}"><strong>${latest.correct?'Correct answer ✓':'Keep practising'}</strong><p>${esc(latest.prompt)}</p><p>Answer: ${esc(latest.answer)}${latest.explanation?`<br>${esc(latest.explanation)}`:''}</p></div>`:'';
  if(m.myTurn)renderTurn(m,panel);
  else panel.innerHTML=`<span class="eyebrow">${m.finished||m.cancelled?'Match complete':'Waiting for the next move'}</span><h2>${m.finished||m.cancelled?esc(m.outcome):`${esc(m.players[m.currentActor].name)} is up.`}</h2><p>${m.finished||m.cancelled?'Your results have been saved.':'You can leave this screen. The match stays in your inbox, and enabled notifications will let you know when it’s your turn.'}</p>${m.actor?feedback:''}<button class="secondary" id="refresh-match">Refresh match</button>`;
  click('#refresh-match',()=>openMatch(m.teacherId,m.id));
  const isTeacher=dashboard?.user.role==='teacher' && m.teacherId===session.id;
  if(m.actor && m.feedback.length)document.getElementById('match-review').innerHTML=`<section class="card"><h2>Your English progress</h2><p>${m.accuracy[m.actor].correct} of ${m.accuracy[m.actor].total} answers correct.</p><details ${afterSubmit?'open':''}><summary>Review your answers</summary>${m.feedback.slice().reverse().map(f=>`<div class="feedback ${f.correct?'':'incorrect'}"><strong>${f.correct?'Correct ✓':'Keep practising'}</strong><p>${esc(f.prompt)}</p><p>Your answer: ${esc(f.submitted)}<br>Correct answer: ${esc(f.answer)}<br>${esc(f.explanation)}</p></div>`).join('')}</details></section>`;
  if(isTeacher){document.getElementById('match-review').innerHTML=`<section class="card"><h2>Teacher review</h2><div class="toolbar">${!m.finished&&!m.cancelled?'<button class="secondary" id="remind-match">Remind next player</button><button class="danger" id="cancel-match">End match</button>':'<button class="danger" id="delete-match">Delete saved results</button>'}</div><div class="table-wrap"><table><thead><tr><th>Player</th><th>Question</th><th>Answer given</th><th>Result</th></tr></thead><tbody>${m.feedback.map(f=>`<tr><td>${esc(m.players[f.actor].name)}</td><td>${esc(f.prompt)}</td><td>${esc(f.submitted)}</td><td>${f.correct?'Correct':`Expected: ${esc(f.answer)}`}</td></tr>`).join('')}</tbody></table></div></section>`;click('#remind-match',async()=>{await api('remind',{matchId:m.id});notice('Reminder queued for the student’s enabled notification channels.');});click('#cancel-match',async()=>{if(confirm('End this match now? Current results will be kept.')){await api('cancel-match',{matchId:m.id});await openMatch(m.teacherId,m.id);}});click('#delete-match',async()=>{if(confirm('Permanently delete this match’s results? Export results first if needed.')){await api('delete-match',{matchId:m.id});await home();}});}
  if(!m.finished&&!m.cancelled)polling=setInterval(async()=>{if(document.hidden||routeId!==view)return;try{const {match}=await api('match',{teacherId:m.teacherId,matchId:m.id});if(routeId===view&&(match.version!==m.version||match.cancelled))renderMatch(match);}catch{}},15000);
  if(afterSubmit&&m.history.length)playReplay(m.history.at(-1));
}
async function playReplay(replay){if(!replay||!scene)return;const activeScene=scene;const view=routeId;const skip=document.getElementById('skip-replay');const button=document.getElementById('play-last-replay');button.disabled=true;skip.hidden=false;await activeScene.playReplay(replay);if(view===routeId){skip.hidden=true;button.disabled=false;}}
function renderTurn(m,panel){const q=m.turn.question;const moves=m.gameType==='penalty'?PENALTY_MOVES:TURKEY_MOVES;
  panel.innerHTML=`<span class="eyebrow">Your turn · ${m.role==='striker'?'shooter':m.role==='keeper'?'goalkeeper':m.role}</span><h2>Earn your move.</h2><p class="muted">A correct answer activates your move. Lock your answer and your choices together.</p><form id="student-turn"><p class="question-prompt">${esc(q.prompt)}</p>${q.type==='gap-fill'?'<label>Your answer<input name="answer" maxlength="500" autocomplete="off" required></label>':`<div class="choices" aria-label="Answer choices">${q.options.map((o,i)=>`<button type="button" data-answer="${i}" aria-pressed="false">${esc(o)}</button>`).join('')}</div><input type="hidden" name="answer" required>`}${m.gameType==='sniper'?`<label>Your emergence spot<select name="emergence" required><option value="">Choose cover</option>${SNIPER_SPOTS.map(s=>`<option value="${s}">${title(s)}</option>`).join('')}</select></label><label>Predict the opponent’s spot<select name="target" required><option value="">Choose a prediction</option>${SNIPER_SPOTS.map(s=>`<option value="${s}">${title(s)}</option>`).join('')}</select></label>`:`<label>${m.gameType==='penalty'?'Choose a target zone':'Choose an attack or defence'}<select name="move" required><option value="">Choose a move</option>${moves.map(s=>`<option value="${s}">${title(s)}</option>`).join('')}</select></label>${m.gameType==='turkey'?'<small>Counter stops Peck and Charge and returns 8 damage. It still takes 12 from Wing Slap.</small>':''}`}<button class="primary" type="submit" style="width:100%;margin-top:20px">Lock answer & move →</button><p class="account-note">Your choice is final once saved.</p></form>`;
  const f=document.getElementById('student-turn');click('[data-answer]',el=>{f.elements.answer.value=q.options[Number(el.dataset.answer)];panel.querySelectorAll('[data-answer]').forEach(b=>b.setAttribute('aria-pressed',String(b===el)));});
  busyForm('student-turn',async data=>{if(!String(data.get('answer')||'').trim())throw new Error('Choose an answer first.');const result=await api('submit',{teacherId:m.teacherId,matchId:m.id,version:m.turn.version,turnId:m.turn.id,answer:data.get('answer'),move:data.get('move'),emergence:data.get('emergence'),target:data.get('target')});renderMatch(result.match,Boolean(result.replay));notice(result.match.feedback.at(-1)?.correct?'Correct. Your move is active.':'Answer saved. Review the correct answer below.');});
}
async function notificationDialog(){
  document.getElementById('notifications-dialog')?.remove();const d=document.createElement('dialog');d.id='notifications-dialog';d.innerHTML=`<h2>Your notifications</h2><p>Match assignments and new turns always appear in your inbox.</p><p id="push-status">${dashboard.capabilities.push?'Turn on device notifications to receive alerts outside the app.':'Push notifications are awaiting server setup. Your inbox still works.'}</p><div class="toolbar"><button class="primary" id="enable-push" ${!dashboard.capabilities.push?'disabled':''}>Enable on this device</button><button class="secondary" id="disable-push">Disable on this device</button></div><form id="preferences-form"><label class="check"><input type="checkbox" name="emailReminders" ${dashboard.preferences.emailReminders?'checked':''}>Also send reminders to my account email</label><button class="secondary" type="submit">Save email preference</button></form><p class="account-note">On iPhone or iPad, add the app to your Home Screen first, then open it there to enable notifications.</p><button class="quiet" id="close-notifications">Close</button>`;document.body.append(d);d.showModal();click('#close-notifications',()=>d.close());busyForm('preferences-form',async data=>{await api('preferences',{emailReminders:data.get('emailReminders')==='on'});dashboard=await api();notice('Notification preference saved.');});
  click('#enable-push',async()=>{
    if(!('serviceWorker' in navigator) || !('PushManager' in window) || !('Notification' in window))throw new Error('This browser cannot receive push notifications here. Use your match inbox, or open the installed app.');
    if(await Notification.requestPermission()!=='granted')throw new Error('Notifications are off. You can change this in your browser settings.');
    const registration=await navigator.serviceWorker.ready;const key=dashboard.capabilities.vapidPublicKey;const bytes=Uint8Array.from(atob(key.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
    const subscription=await registration.pushManager.getSubscription() || await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});
    await api('subscribe',{subscription:subscription.toJSON()});document.getElementById('push-status').textContent='Notifications are enabled on this device.';notice('Device notifications enabled.');
  });
  click('#disable-push',async()=>{if(!('serviceWorker' in navigator))return;const r=await navigator.serviceWorker.ready;const sub=await r.pushManager.getSubscription();if(sub){await api('unsubscribe',{subscription:{endpoint:sub.endpoint}});await sub.unsubscribe();}document.getElementById('push-status').textContent='Notifications are disabled on this device.';});
}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;document.getElementById('install-app').hidden=false;});click('#install-app',async()=>{await installPrompt?.prompt();installPrompt=null;document.getElementById('install-app').hidden=true;});
window.addEventListener('offline',()=>notice('You’re offline. Your saved match is safe. Reconnect before submitting a turn.',true));
window.addEventListener('online',()=>notice('Back online. You can continue your match.'));
if('serviceWorker' in navigator)navigator.serviceWorker.register('/classroom-sw.js').catch(()=>{});
try{
  const callback=await handleAuthCallback();session=await getUser();
  if(callback?.type==='recovery'||callback?.type==='invite')await passwordScreen(callback);
  else if(session){const match=params.get('match'),teacher=params.get('teacher');await home();if(match&&teacher)await openMatch(teacher,match);}
  else await showAuth();
}catch(error){await showAuth(error.message);}
onAuthChange(event=>{if(event==='logout'){session=null;dashboard=null;showAuth();}});
