import test from 'node:test';import assert from 'node:assert/strict';
import {parseQuestionText,parsePoolJson,parseCsv,validateQuestion,DOCUMENT_EXAMPLE} from '../question-import.mjs';
import {makePoolStore} from '../question-pools.mjs';
test('document parser preserves options, supplied answers and gap/true-false questions',()=>{const qs=parseQuestionText(DOCUMENT_EXAMPLE);assert.equal(qs.length,3);assert.equal(qs[0].answer,'has worked');assert.equal(qs[1].answer,'at');assert.equal(qs[2].type,'true-false');qs.forEach(q=>assert.deepEqual(validateQuestion(q),[]));});
test('five options and a separate answer key are supported; missing answers stay missing',()=>{const qs=parseQuestionText('1. Choose a word.\nA) one\nB) two\nC) three\nD) four\nE) five\n2. Missing answer\n\nAnswer key:\n1-E');assert.equal(qs[0].answer,'five');assert.equal(qs[0].options.length,5);assert.equal(qs[1].answer,'');assert.ok(validateQuestion(qs[1]).length);});
test('CSV handles quoted commas and newlines, reports broken quotes and never discards invalid rows',()=>{const qs=parseCsv('question,type,option_a,option_b,answer\n"Hello,\nworld?",multiple-choice,yes,no,yes\nMissing,gap-fill,,,');assert.equal(qs.length,2);assert.equal(qs[0].prompt,'Hello,\nworld?');assert.ok(validateQuestion(qs[1]).length);assert.throws(()=>parseCsv('question,answer\n"broken,yes'),/unclosed/);});
test('question pool exports can be reimported; invalid answers and duplicates are rejected',()=>{const q=parsePoolJson(JSON.stringify([{prompt:'Pick',type:'multiple-choice',options:['A','B'],answer:'C'}]))[0];assert.ok(validateQuestion(q).some(s=>s.includes('match')));assert.ok(validateQuestion({...q,options:['same','Same'],answer:'same'}).some(s=>s.includes('different')));assert.throws(()=>parsePoolJson('{}'),/array/);});
test('named pools preserve original questions and make only selected pool active',()=>{const map=new Map([['mailgames.questions.v1',JSON.stringify([{id:'old'}])]]);const storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};const pools=makePoolStore(storage);const id=pools.create('Unit 1',[{id:'new'}]);assert.equal(pools.list().pools[0].questions[0].id,'old');assert.equal(JSON.parse(storage.getItem('mailgames.questions.v1'))[0].id,'new');pools.select('original');pools.saveQuestions([{id:'edited'}]);pools.select(id);assert.equal(JSON.parse(storage.getItem('mailgames.questions.v1'))[0].id,'new');});
test('storage failure does not replace the active pool',()=>{const map=new Map([['mailgames.questions.v1','[]']]);let fail=true;const storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>{if(k==='mailgames.questions.v1'&&fail){fail=false;throw new Error('quota');}map.set(k,v);},removeItem:k=>map.delete(k)};const pools=makePoolStore(storage);assert.throws(()=>pools.create('No space',[{id:'new'}]),/quota/);assert.equal(storage.getItem('mailgames.questions.v1'),'[]');assert.equal(storage.getItem('mailgames.pools.v1'),null);});
